name: flutter_exprtk
description: flutter_exprtk is a FFI wrapper for the exptrk Mathematical Expression Toolkit Library
version: 0.0.5
repository: https://github.com/DominikStarke/flutter_exprtk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.dost.flutter_exprtk
        pluginClass: FlutterExprtkPlugin
      ios:
        pluginClass: SwiftFlutterExprtkPlugin
      macos:
        pluginClass: FlutterExprtkPlugin
      windows:
        pluginClass: FlutterExprtkPlugin
