name: NAME_platform_interface
description: A common platform interface for the NAME plugin.
repository: GITHUB/tree/master/NAME_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: VERSION

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0